apiVersion: apps/v1beta1
kind: Deployment
metadata:
 name: niko-app
spec:
 selector:
   matchLabels:
     app: niko-app
 replicas: 2 # tells deployment to run 2 pods matching the template
 template: # create pods using pod definition in this template
   metadata:
     labels:
       app: niko-app
   spec:
     containers:
     - name: niko-app
       image: gcr.io/dd-decaf-cfbf6/nikos-awesome-nodejs-app
       env:
          - name: SECRET_USERNAME
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: username
          - name: SECRET_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: password
       ports:
       - containerPort: 8000